[database]

## Doesn't support multiple hosts or clusters
## Default to localhost:27017

#host = "127.0.0.1:27017"

## If not specified, default to the "test" database.

database = "gwentapi"

	## If authentication is enabled on your mongod comment out these lines.
	## If authenticationDatabase is left empty it is defaulted 
	## to the value of "database" if set, otherwise "admin".

	[database.authentication]
	#username = "client"
	#password = "thereisonlyonekinginthenorth"
	#authenticationDatabase = "admin"

[app]
LogInfoFile = "./info.log"
LogErrorFile = "./error.log"
debug = false
verbose = false

## The base URL to which the application is made available.
## Every URL linking to a resource will point to it.

baseURL = "http://localhost:8080"

## Path on the server pointing to the location of the folder
## containing the artworks for the cards.
## "./media" by default.

mediaPath = "./media"
