[database]
host = "127.0.0.1:27017"
	[database.authentication]
	#username = "client"
	#password = "thereisonlyonekinginthenorth"
	#authenticationDatabase = "admin"

[app]
LogInfoFile = "./info.log"
LogErrorFile = "./error.log"
debug = false
verbose = false
baseURL= "http://localhost:8080"
dbName = "gwentapi"