[App]
  Debug = false
  Verbose = false
  LogInfoFile = "./info.log"
  LogErrorFile = "./error.log"
  PublicURL = "http://localhost:8080"
  Port = ":8080"
  MediaPath = "./media"

[Database]
  Addrs = ["127.0.0.1:27017"]
  Database = "gwentTest"
  useSSLProtocol = false
  [Database.Authentication]
